package com.example.demo.enums;

public enum Edition {
	
	
	LES_FRICHES_D_ELDRAINE,
	LES_CAVERNES_OUBLIÉES_D_IXALAN,
	RAVNICA_REMASTERED,
	MURDERS_AT_KARLOV_MANOR, 
	OUTLAWS_OF_THUNDER_JUNCTION,
	MODERN_HORIZONS_3,
	BLOOMBURROW,
	DUSKMOURN_HOUSE_OF_HORROR,
	UNIVERSES_BEYOND_ASSASSINS_CREED,
	UNIVERSES_BEYOND_FALLOUT
}
